# Generated by Django 4.1.3 on 2023-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_variation_variation_category"),
        ("carts", "0002_alter_cart_cart_id_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
